### ISSUE TITLE
New Show Request: WWE

### ISSUE THREAD

**Issue by ajaybhargav** [ajdeveloped/plugin.video.tvondesizonexl#3]
Can you please add WWE shows to the list?

**Comment by jchirag0221** [comment]
Hi ajaybhargav.. This has been added in 2.5.6. Also select "Force TV Shows data refresh next time when add-on starts" so that it can fetch the shows for WWE.

**Comment by ajaybhargav** [comment]
Who is updating it.. and where? I don't see it getting updated on gihub? Is the development going outside?

**Comment by jchirag0221** [comment]
Hi,

AJ has given me access to googlecode.

Not sure who is updating github. But I have ask AJ to give me access to github so that I can also update github along with googlecode. Waiting for his reply. 

Not sure who you are using github as the superrepo - aj newlook repo is working off googlecode and everyone is getting updates via googlecode. 

Email me on chirag@chiragjhaveri.com if you are stuck. 









-------- Original message --------

**Comment by ajaybhargav** [comment]
I was actually downloading zip from github. Can you please share google code link or repo link?

**Comment by jchirag0221** [comment]
Hi,

I have just got access to github repo. 

I will update that sometime today. 

However the best way is to use googlecode as by using that you will automatically get latest updates whenever there is new release. 

Regards
Chirag 


Sent on the go with Vodafone


-------- Original message --------

**Comment by ajaybhargav** [comment]
But I dont know the repo link. Should I use Fusion repo to keep plugin updated?

**Comment by jchirag0221** [comment]
Hi ,

Just add http://srp.nu as a file in xbmc under systems - file manager. 

And then download the superrepo for your version of xbmc. 

Once you download , install aj addon nrw look repo from Superrepo. 

And using aj addon new look you can install tv on desizone. 

Let me know if you need more help. 

Regards
Chirag


Sent on the go with Vodafone


-------- Original message --------

**Comment by jchirag0221** [comment]
Hi. 

AJ has given me the access to update the github code. 

I will update that sometime today. 

Send me your email address so that I can send you steps on how to install superrepo and aj addon repo. 

Also let me know which version of xbmc you are running and what is the OS ?


Sent on the go with Vodafone


-------- Original message --------

**Comment by jchirag0221** [comment]
Hi, The addon has been updated in github. WWE has now been added.

**Comment by jchirag0221** [comment]
Hi, 

Please follow the steps shown in below link to install superrepo


https://superrepo.org/get-started/

Then go to - SYSTEM - ADDON - Get Addon - Superepo - Addon repository- AJ Addon new look and install that repo

Once the repo is enabled. 

Go to SYSTEM - ADDON - Get Addon - right click and do force refresh on aj addon new look repository. 

Wait for 3-4 munutes and not click on on the repo and go to video addons and install tv on desizone. 

Please email me directly on chirag@chiragjhaveri.com if you have any issues with the screenshot if you get stuck. 

Regards
Chirag 

Sent on the go with Vodafone


-------- Original message --------
From: Chirag Jhaveri <tapaskaro@yahoo.com> 
Date: 14/01/2015  7:16 PM  (GMT+10:00) 
To: "ajdeveloped/plugin.video.tvondesizonexl" <reply@reply.github.com> 
Subject: Re: [plugin.video.tvondesizonexl] New Show Request: WWE (#3) 

Hi. 

AJ has given me the access to update the github code. 

I will update that sometime today. 

Send me your email address so that I can send you steps on how to install superrepo and aj addon repo. 

Also let me know which version of xbmc you are running and what is the OS ?


Sent on the go with Vodafone

**Comment by ajaybhargav** [comment]
I do have super repo. I will install it from there. Thanks for updating this addon.
